/*
 * generated by Xtext 2.14.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.MQLApplication.ui.internal.MQLApplicationActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MQLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MQLApplicationActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MQLApplicationActivator activator = MQLApplicationActivator.getInstance();
		return activator != null ? activator.getInjector(MQLApplicationActivator.ORG_XTEXT_MQL) : null;
	}

}
