/*
 * generated by Xtext 2.14.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MQLStandaloneSetup extends MQLStandaloneSetupGenerated {

	def static void doSetup() {
		new MQLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
