/**
 */
package qmm.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test suite for the '<em><b>qmm</b></em>' package.
 * <!-- end-user-doc -->
 * @generated
 */
public class QmmTests extends TestSuite {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(suite());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static Test suite() {
		TestSuite suite = new QmmTests("qmm Tests");
		suite.addTestSuite(AttributeFamilyTest.class);
		suite.addTestSuite(AttributeNameMappingTest.class);
		suite.addTestSuite(AttributeTest.class);
		suite.addTestSuite(AttributeLibTest.class);
		suite.addTestSuite(AttributeValueRequirementTest.class);
		suite.addTestSuite(CAEXBasicObjectTest.class);
		suite.addTestSuite(CAEXFileTest.class);
		suite.addTestSuite(CAEXObjectTest.class);
		suite.addTestSuite(DocumentRootTest.class);
		suite.addTestSuite(ExternalInterfaceTest.class);
		suite.addTestSuite(ExternalReferenceTypeTest.class);
		suite.addTestSuite(InstanceHierarchyTest.class);
		suite.addTestSuite(InterfaceClassLibTest.class);
		suite.addTestSuite(InterfaceClassTest.class);
		suite.addTestSuite(InterfaceFamilyTest.class);
		suite.addTestSuite(InterfaceIDMappingTest.class);
		suite.addTestSuite(InternalElementTest.class);
		suite.addTestSuite(InternalLinkTest.class);
		suite.addTestSuite(MappingTest.class);
		suite.addTestSuite(NominalScaledTypeTest.class);
		suite.addTestSuite(OrdinalScaledTypeTest.class);
		suite.addTestSuite(RefSemanticTest.class);
		suite.addTestSuite(RoleClassLibTest.class);
		suite.addTestSuite(RoleClassTest.class);
		suite.addTestSuite(RoleFamilyTest.class);
		suite.addTestSuite(RoleRequirementsTest.class);
		suite.addTestSuite(SourceDocumentInformationTest.class);
		suite.addTestSuite(SupportedRoleClassTest.class);
		suite.addTestSuite(SystemUnitClassLibTest.class);
		suite.addTestSuite(SystemUnitClassTest.class);
		suite.addTestSuite(SystemUnitFamilyTest.class);
		suite.addTestSuite(UnknownTypeTest.class);
		suite.addTestSuite(CopyrightTest.class);
		suite.addTestSuite(DescriptionTest.class);
		suite.addTestSuite(RevisionTest.class);
		suite.addTestSuite(VersionTest.class);
		suite.addTestSuite(AdditionalInformationTest.class);
		suite.addTestSuite(ElementTest.class);
		suite.addTestSuite(GenericElementTest.class);
		suite.addTestSuite(GenericAttributeTest.class);
		suite.addTestSuite(AttributeDataType_And_BitOperatorTest.class);
		suite.addTestSuite(Object_Character_toString_FunctionalOperatorTest.class);
		suite.addTestSuite(OrdinalScaledType_requiredMaxValue_AttrEClassTest.class);
		suite.addTestSuite(InstanceHierarchy_Reference_OrGroupTest.class);
		suite.addTestSuite(CAEXObject_name_AttrEClassTest.class);
		suite.addTestSuite(GenericElement_elementFeatureMap_AttrEClassTest.class);
		suite.addTestSuite(ExternalInterface_Containment_OrGroupTest.class);
		suite.addTestSuite(Element_value_AttrEClassTest.class);
		suite.addTestSuite(CAEXObject_iD_AttrEClassTest.class);
		suite.addTestSuite(Object_CalculateableParameterTest.class);
		suite.addTestSuite(AttributeValueRequirement_Reference_OrGroupTest.class);
		suite.addTestSuite(InstanceHierarchy_Containment_OrGroupTest.class);
		suite.addTestSuite(RefSemantic_correspondingAttributePath_AttrEClassTest.class);
		suite.addTestSuite(Object_Character_hashCode_FunctionalOperatorTest.class);
		suite.addTestSuite(Number_Integer_Object_Number_equals_FunctionalOperatorTest.class);
		suite.addTestSuite(IntegerParseInt_ClassOperatorTest.class);
		suite.addTestSuite(Element_Containment_OrGroupTest.class);
		suite.addTestSuite(GenericAttribute_Containment_OrGroupTest.class);
		suite.addTestSuite(DateTime_PrimitiveArgumentTest.class);
		suite.addTestSuite(trim_FunctionalOperatorTest.class);
		suite.addTestSuite(Double_FunctionalParameterTest.class);
		suite.addTestSuite(toString_FunctionalOperatorTest.class);
		suite.addTestSuite(AttributeFamily_Containment_OrGroupTest.class);
		suite.addTestSuite(SystemUnitClass_refBaseClassPath_AttrEClassTest.class);
		suite.addTestSuite(CountableReferenceParameterTest.class);
		suite.addTestSuite(GenericElement_attributeFeatureMap_AttrEClassTest.class);
		suite.addTestSuite(indexOfCharFromIndex_FunctionalOperatorTest.class);
		suite.addTestSuite(Number_Double_smallerEquals_FunctionalOperatorTest.class);
		suite.addTestSuite(Character_And_BitOperatorTest.class);
		suite.addTestSuite(InterfaceIDMapping_roleInterfaceID_AttrEClassTest.class);
		suite.addTestSuite(CAEXObject_Containment_OrGroupTest.class);
		suite.addTestSuite(SourceDocumentInformation_originVendor_AttrEClassTest.class);
		suite.addTestSuite(Mapping_Containment_OrGroupTest.class);
		suite.addTestSuite(UnknownType_Containment_OrGroupTest.class);
		suite.addTestSuite(ExternalReferenceType_alias_AttrEClassTest.class);
		suite.addTestSuite(String_PrimitiveArgumentTest.class);
		suite.addTestSuite(Version_Reference_OrGroupTest.class);
		suite.addTestSuite(CharSequence_And_BitOperatorTest.class);
		suite.addTestSuite(Version_Containment_OrGroupTest.class);
		suite.addTestSuite(toLowerCase_FunctionalOperatorTest.class);
		suite.addTestSuite(smallerEquals_FunctionalOperatorTest.class);
		suite.addTestSuite(OrdinalScaledType_requiredValue_AttrEClassTest.class);
		suite.addTestSuite(CharSequence_Or_BitOperatorTest.class);
		suite.addTestSuite(Boolean_PrimitiveArgumentTest.class);
		suite.addTestSuite(SourceDocumentInformation_Reference_OrGroupTest.class);
		suite.addTestSuite(RoleRequirements_Reference_OrGroupTest.class);
		suite.addTestSuite(AdditionalInformation_Containment_OrGroupTest.class);
		suite.addTestSuite(AttributeNameMapping_roleAttributeName_AttrEClassTest.class);
		suite.addTestSuite(Number_FunctionalParameterTest.class);
		suite.addTestSuite(AttributeDataType_FunctionalParameterTest.class);
		suite.addTestSuite(endsWith_FunctionalOperatorTest.class);
		suite.addTestSuite(Or_EvaluationBitOperatorTest.class);
		suite.addTestSuite(hashCode_FunctionalOperatorTest.class);
		suite.addTestSuite(Object_CharSequence_equals_FunctionalOperatorTest.class);
		suite.addTestSuite(offsetByCodePoints_FunctionalOperatorTest.class);
		suite.addTestSuite(AttributeNameMapping_Reference_OrGroupTest.class);
		suite.addTestSuite(Object_CharSequence_toString_FunctionalOperatorTest.class);
		suite.addTestSuite(CharSequence_String_Object_CharSequence_toString_FunctionalOperatorTest.class);
		suite.addTestSuite(indexOfChar_FunctionalOperatorTest.class);
		suite.addTestSuite(InterfaceClassLib_Reference_OrGroupTest.class);
		suite.addTestSuite(String_CalculateableParameterTest.class);
		suite.addTestSuite(CAEXFile_schemaVersion_AttrEClassTest.class);
		suite.addTestSuite(Character_CalculateableParameterTest.class);
		suite.addTestSuite(Attribute_unit_AttrEClassTest.class);
		suite.addTestSuite(Element_Reference_OrGroupTest.class);
		suite.addTestSuite(Object_Boolean_equals_FunctionalOperatorTest.class);
		suite.addTestSuite(AttributeDataType_CalculateableParameterTest.class);
		suite.addTestSuite(Double_And_BitOperatorTest.class);
		suite.addTestSuite(InterfaceClass_Containment_OrGroupTest.class);
		suite.addTestSuite(InterfaceFamily_Reference_OrGroupTest.class);
		suite.addTestSuite(Version_value_AttrEClassTest.class);
		suite.addTestSuite(ExternalReferenceType_Reference_OrGroupTest.class);
		suite.addTestSuite(GenericElement_Containment_OrGroupTest.class);
		suite.addTestSuite(RefSemantic_Reference_OrGroupTest.class);
		suite.addTestSuite(Revision_newVersion_AttrEClassTest.class);
		suite.addTestSuite(Attribute_value_AttrEClassTest.class);
		suite.addTestSuite(AttributeValueRequirement_name_AttrEClassTest.class);
		suite.addTestSuite(ExternalInterface_Reference_OrGroupTest.class);
		suite.addTestSuite(SourceDocumentInformation_originVersion_AttrEClassTest.class);
		suite.addTestSuite(SupportedRoleClass_Reference_OrGroupTest.class);
		suite.addTestSuite(contains_FunctionalOperatorTest.class);
		suite.addTestSuite(SourceDocumentInformation_originVendorURL_AttrEClassTest.class);
		suite.addTestSuite(SourceDocumentInformation_originRelease_AttrEClassTest.class);
		suite.addTestSuite(SourceDocumentInformation_originName_AttrEClassTest.class);
		suite.addTestSuite(AttributeLib_Reference_OrGroupTest.class);
		suite.addTestSuite(DateTime_CalculateableElementReferenceArgumentTest.class);
		suite.addTestSuite(Version_changeMode_AttrEClassTest.class);
		suite.addTestSuite(EFeatureMapEntry_CalculateableParameterTest.class);
		suite.addTestSuite(SystemUnitClass_Containment_OrGroupTest.class);
		suite.addTestSuite(CharSequence_CalculateableParameterTest.class);
		suite.addTestSuite(CharSequence_String_Object_CharSequence_equals_FunctionalOperatorTest.class);
		suite.addTestSuite(String_And_BitOperatorTest.class);
		suite.addTestSuite(UnknownType_requirements_AttrEClassTest.class);
		suite.addTestSuite(GenericAttribute_Reference_OrGroupTest.class);
		suite.addTestSuite(NominalScaledType_Containment_OrGroupTest.class);
		suite.addTestSuite(InterfaceClass_refBaseClassPath_AttrEClassTest.class);
		suite.addTestSuite(GenericElement_Reference_OrGroupTest.class);
		suite.addTestSuite(startsWith_FunctionalOperatorTest.class);
		suite.addTestSuite(String_CalculateableElementReferenceArgumentTest.class);
		suite.addTestSuite(Attribute_defaultValue_AttrEClassTest.class);
		suite.addTestSuite(substring_FunctionalOperatorTest.class);
		suite.addTestSuite(NominalScaledType_Reference_OrGroupTest.class);
		suite.addTestSuite(CharSequence_PrimitiveArgumentTest.class);
		suite.addTestSuite(Count_AggregationOperatorTest.class);
		suite.addTestSuite(Number_Double_Object_Number_toString_FunctionalOperatorTest.class);
		suite.addTestSuite(Attribute_Reference_OrGroupTest.class);
		suite.addTestSuite(AttributeDataType_PrimitiveArgumentTest.class);
		suite.addTestSuite(CAEXBasicObject_Containment_OrGroupTest.class);
		suite.addTestSuite(codePointAt_FunctionalOperatorTest.class);
		suite.addTestSuite(Description_value_AttrEClassTest.class);
		suite.addTestSuite(SourceDocumentInformation_originID_AttrEClassTest.class);
		suite.addTestSuite(DateTime_FunctionalParameterTest.class);
		suite.addTestSuite(Revision_Containment_OrGroupTest.class);
		suite.addTestSuite(Min_AggregationOperator_DoubleTest.class);
		suite.addTestSuite(InternalElement_Containment_OrGroupTest.class);
		suite.addTestSuite(Object_CharSequence_hashCode_FunctionalOperatorTest.class);
		suite.addTestSuite(Boolean_And_BitOperatorTest.class);
		suite.addTestSuite(isEmpty_FunctionalOperatorTest.class);
		suite.addTestSuite(String_FunctionalParameterTest.class);
		suite.addTestSuite(InterfaceClassLib_Containment_OrGroupTest.class);
		suite.addTestSuite(Copyright_value_AttrEClassTest.class);
		suite.addTestSuite(greaterThan_FunctionalOperatorTest.class);
		suite.addTestSuite(SystemUnitClassLib_Reference_OrGroupTest.class);
		suite.addTestSuite(startsWithOffset_FunctionalOperatorTest.class);
		suite.addTestSuite(indexOfString_FunctionalOperatorTest.class);
		suite.addTestSuite(Number_Integer_greaterThan_FunctionalOperatorTest.class);
		suite.addTestSuite(NominalScaledType_requiredValue_AttrEClassTest.class);
		suite.addTestSuite(DocumentRoot_Reference_OrGroupTest.class);
		suite.addTestSuite(AttributeDataType_CalculateableElementReferenceArgumentTest.class);
		suite.addTestSuite(SourceDocumentInformation_lastWritingDateTime_AttrEClassTest.class);
		suite.addTestSuite(Integer_And_BitOperatorTest.class);
		suite.addTestSuite(CAEXBasicObject_changeMode_AttrEClassTest.class);
		suite.addTestSuite(Double_Or_BitOperatorTest.class);
		suite.addTestSuite(Element_name_AttrEClassTest.class);
		suite.addTestSuite(RoleClass_Reference_OrGroupTest.class);
		suite.addTestSuite(SourceDocumentInformation_originProjectID_AttrEClassTest.class);
		suite.addTestSuite(RoleClass_Containment_OrGroupTest.class);
		suite.addTestSuite(Object_FunctionalParameterTest.class);
		suite.addTestSuite(EFeatureMapEntry_FunctionalParameterTest.class);
		suite.addTestSuite(Number_Integer_Object_Number_hashCode_FunctionalOperatorTest.class);
		suite.addTestSuite(EFeatureMapEntry_Or_BitOperatorTest.class);
		suite.addTestSuite(CharSequence_String_length_FunctionalOperatorTest.class);
		suite.addTestSuite(InterfaceIDMapping_Containment_OrGroupTest.class);
		suite.addTestSuite(equalsIgnoreCase_FunctionalOperatorTest.class);
		suite.addTestSuite(AttributeNameMapping_Containment_OrGroupTest.class);
		suite.addTestSuite(Revision_authorName_AttrEClassTest.class);
		suite.addTestSuite(AttributeLib_Containment_OrGroupTest.class);
		suite.addTestSuite(DocumentRoot_Containment_OrGroupTest.class);
		suite.addTestSuite(RoleClassLib_Containment_OrGroupTest.class);
		suite.addTestSuite(RoleFamily_Containment_OrGroupTest.class);
		suite.addTestSuite(Number_CalculateableParameterTest.class);
		suite.addTestSuite(InternalLink_Containment_OrGroupTest.class);
		suite.addTestSuite(DocumentRoot_mixed_AttrEClassTest.class);
		suite.addTestSuite(Max_AggregationOperator_IntegerTest.class);
		suite.addTestSuite(Description_changeMode_AttrEClassTest.class);
		suite.addTestSuite(Number_PrimitiveArgumentTest.class);
		suite.addTestSuite(Object_Number_toString_FunctionalOperatorTest.class);
		suite.addTestSuite(CAEXFile_superiorStandardVersion_AttrEClassTest.class);
		suite.addTestSuite(AttributeFamily_Reference_OrGroupTest.class);
		suite.addTestSuite(doubleValue_FunctionalOperatorTest.class);
		suite.addTestSuite(InternalLink_refPartnerSideA_AttrEClassTest.class);
		suite.addTestSuite(Number_Double_Object_Number_equals_FunctionalOperatorTest.class);
		suite.addTestSuite(parseBoolean_FunctionalOperatorTest.class);
		suite.addTestSuite(toUpperCase_FunctionalOperatorTest.class);
		suite.addTestSuite(Object_Boolean_toString_FunctionalOperatorTest.class);
		suite.addTestSuite(Revision_comment_AttrEClassTest.class);
		suite.addTestSuite(CAEXFile_Containment_OrGroupTest.class);
		suite.addTestSuite(Sum_AggregationOperator_IntegerTest.class);
		suite.addTestSuite(greaterEquals_FunctionalOperatorTest.class);
		suite.addTestSuite(InternalLink_refPartnerSideB_AttrEClassTest.class);
		suite.addTestSuite(Character_FunctionalParameterTest.class);
		suite.addTestSuite(RoleFamily_Reference_OrGroupTest.class);
		suite.addTestSuite(Attribute_attributeDataType_AttrEClassTest.class);
		suite.addTestSuite(Description_Reference_OrGroupTest.class);
		suite.addTestSuite(Object_Number_hashCode_FunctionalOperatorTest.class);
		suite.addTestSuite(InterfaceIDMapping_Reference_OrGroupTest.class);
		suite.addTestSuite(Number_Integer_smallerEquals_FunctionalOperatorTest.class);
		suite.addTestSuite(CAEXBasicObject_Reference_OrGroupTest.class);
		suite.addTestSuite(Attribute_refAttributeType_AttrEClassTest.class);
		suite.addTestSuite(compareToString_FunctionalOperatorTest.class);
		suite.addTestSuite(InternalElement_Reference_OrGroupTest.class);
		suite.addTestSuite(OrdinalScaledType_requiredMinValue_AttrEClassTest.class);
		suite.addTestSuite(Boolean_Or_BitOperatorTest.class);
		suite.addTestSuite(Character_Or_BitOperatorTest.class);
		suite.addTestSuite(Boolean_FunctionalParameterTest.class);
		suite.addTestSuite(Double_PrimitiveArgumentTest.class);
		suite.addTestSuite(compareToStringIgnoreCase_FunctionalOperatorTest.class);
		suite.addTestSuite(InterfaceClass_Reference_OrGroupTest.class);
		suite.addTestSuite(Object_Or_BitOperatorTest.class);
		suite.addTestSuite(AdditionalInformation_Reference_OrGroupTest.class);
		suite.addTestSuite(Countable_ReferenceArgumentTest.class);
		suite.addTestSuite(CharSequence_FunctionalParameterTest.class);
		suite.addTestSuite(Boolean_CalculateableParameterTest.class);
		suite.addTestSuite(SourceDocumentInformation_originProjectTitle_AttrEClassTest.class);
		suite.addTestSuite(Number_Or_BitOperatorTest.class);
		suite.addTestSuite(Max_AggregationOperator_DoubleTest.class);
		suite.addTestSuite(SystemUnitFamily_Containment_OrGroupTest.class);
		suite.addTestSuite(Number_Double_greaterThan_FunctionalOperatorTest.class);
		suite.addTestSuite(Copyright_Reference_OrGroupTest.class);
		suite.addTestSuite(Character_PrimitiveArgumentTest.class);
		suite.addTestSuite(RoleClass_refBaseClassPath_AttrEClassTest.class);
		suite.addTestSuite(Copyright_Containment_OrGroupTest.class);
		suite.addTestSuite(AttributeDataType_Or_BitOperatorTest.class);
		suite.addTestSuite(OrdinalScaledType_Containment_OrGroupTest.class);
		suite.addTestSuite(ExternalReferenceType_Containment_OrGroupTest.class);
		suite.addTestSuite(Integer_FunctionalParameterTest.class);
		suite.addTestSuite(ExternalReferenceType_path_AttrEClassTest.class);
		suite.addTestSuite(Object_Boolean_hashCode_FunctionalOperatorTest.class);
		suite.addTestSuite(And_EvaluationBitOperatorTest.class);
		suite.addTestSuite(smallerThan_FunctionalOperatorTest.class);
		suite.addTestSuite(SourceDocumentInformation_Containment_OrGroupTest.class);
		suite.addTestSuite(SystemUnitClass_Reference_OrGroupTest.class);
		suite.addTestSuite(Copyright_changeMode_AttrEClassTest.class);
		suite.addTestSuite(Object_Character_equals_FunctionalOperatorTest.class);
		suite.addTestSuite(Number_Integer_Object_Number_toString_FunctionalOperatorTest.class);
		suite.addTestSuite(EFeatureMapEntry_PrimitiveArgumentTest.class);
		suite.addTestSuite(InterfaceIDMapping_systemUnitInterfaceID_AttrEClassTest.class);
		suite.addTestSuite(DateTime_CalculateableParameterTest.class);
		suite.addTestSuite(InternalElement_refBaseSystemUnitPath_AttrEClassTest.class);
		suite.addTestSuite(charAt_FunctionalOperatorTest.class);
		suite.addTestSuite(Sum_AggregationOperator_DoubleTest.class);
		suite.addTestSuite(compareToBoolean_FunctionalOperatorTest.class);
		suite.addTestSuite(equals_FunctionalOperatorTest.class);
		suite.addTestSuite(Integer_CalculateableParameterTest.class);
		suite.addTestSuite(Number_And_BitOperatorTest.class);
		suite.addTestSuite(codePointBefore_FunctionalOperatorTest.class);
		suite.addTestSuite(Revision_Reference_OrGroupTest.class);
		suite.addTestSuite(Number_Double_smallerThan_FunctionalOperatorTest.class);
		suite.addTestSuite(EFeatureMapEntry_CalculateableElementReferenceArgumentTest.class);
		suite.addTestSuite(Number_Integer_greaterEquals_FunctionalOperatorTest.class);
		suite.addTestSuite(InternalLink_Reference_OrGroupTest.class);
		suite.addTestSuite(Attribute_Containment_OrGroupTest.class);
		suite.addTestSuite(concat_FunctionalOperatorTest.class);
		suite.addTestSuite(EFeatureMapEntry_And_BitOperatorTest.class);
		suite.addTestSuite(SystemUnitFamily_Reference_OrGroupTest.class);
		suite.addTestSuite(SupportedRoleClass_Containment_OrGroupTest.class);
		suite.addTestSuite(InterfaceFamily_Containment_OrGroupTest.class);
		suite.addTestSuite(RoleRequirements_Containment_OrGroupTest.class);
		suite.addTestSuite(Revision_oldVersion_AttrEClassTest.class);
		suite.addTestSuite(Object_Number_equals_FunctionalOperatorTest.class);
		suite.addTestSuite(Number_Integer_smallerThan_FunctionalOperatorTest.class);
		suite.addTestSuite(Number_Double_greaterEquals_FunctionalOperatorTest.class);
		suite.addTestSuite(SystemUnitClassLib_Containment_OrGroupTest.class);
		suite.addTestSuite(AttributeValueRequirement_Containment_OrGroupTest.class);
		suite.addTestSuite(String_Or_BitOperatorTest.class);
		suite.addTestSuite(CAEXObject_Reference_OrGroupTest.class);
		suite.addTestSuite(Integer_Or_BitOperatorTest.class);
		suite.addTestSuite(CAEXFile_Reference_OrGroupTest.class);
		suite.addTestSuite(Mapping_Reference_OrGroupTest.class);
		suite.addTestSuite(DateTime_Or_BitOperatorTest.class);
		suite.addTestSuite(CAEXFile_fileName_AttrEClassTest.class);
		suite.addTestSuite(CharSequence_String_Object_CharSequence_hashCode_FunctionalOperatorTest.class);
		suite.addTestSuite(RoleClassLib_Reference_OrGroupTest.class);
		suite.addTestSuite(Min_AggregationOperator_IntegerTest.class);
		suite.addTestSuite(Integer_PrimitiveArgumentTest.class);
		suite.addTestSuite(RefSemantic_Containment_OrGroupTest.class);
		suite.addTestSuite(OrdinalScaledType_Reference_OrGroupTest.class);
		suite.addTestSuite(Revision_revisionDate_AttrEClassTest.class);
		suite.addTestSuite(Object_And_BitOperatorTest.class);
		suite.addTestSuite(Object_PrimitiveArgumentTest.class);
		suite.addTestSuite(SelectClauseTest.class);
		suite.addTestSuite(DateTime_And_BitOperatorTest.class);
		suite.addTestSuite(Double_CalculateableParameterTest.class);
		suite.addTestSuite(Description_Containment_OrGroupTest.class);
		suite.addTestSuite(length_FunctionalOperatorTest.class);
		suite.addTestSuite(SupportedRoleClass_refRoleClassPath_AttrEClassTest.class);
		suite.addTestSuite(UnknownType_Reference_OrGroupTest.class);
		suite.addTestSuite(Number_Double_Object_Number_hashCode_FunctionalOperatorTest.class);
		suite.addTestSuite(AttributeNameMapping_systemUnitAttributeName_AttrEClassTest.class);
		return suite;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public QmmTests(String name) {
		super(name);
	}

} //QmmTests
