/*
 * generated by Xtext 2.14.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.MQLApplication.ui.internal.MQLApplicationActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MQLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MQLApplicationActivator.getInstance().getInjector("org.xtext.MQL");
	}

}
